// <auto-generated />
namespace Employee.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Intial_MG_Employe_Table_Created : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Intial_MG_Employe_Table_Created));
        
        string IMigrationMetadata.Id
        {
            get { return "202407250349593_Intial_MG_Employe_Table_Created"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
